<%@ Page 
    Language="vb" 
    AutoEventWireup="false" 
    MasterPageFile="~/Design/Site.Master" 
    CodeBehind="~/Design/Site.Master.vb" 
    %>
<%@ MasterType VirtualPath="~/Design/Site.Master" %>

<script runat="server">
	Public ThisPage As MillionLittlePieces.SiteMaster
	Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
		ThisPage = CType(Me.Master, MillionLittlePieces.SiteMaster)
		With ThisPage
			.Properties.Title = "Digital Paintings"
			.Properties.Author = "Paul S Cilwa"
			.Properties.Posted = "08/26/2010"
			.Properties.Description = "All about my newest art form."
			.Properties.Keywords = "Photography"
			.Properties.ThumbnailPath = "FotoSketcher_IMG0034.jpg"
		End With
	End Sub
</script>

<asp:Content ContentPlaceHolderID="CustomPageHead" runat="server" />

<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<p>Software now exists that can take a digital (or digitized) photo 
and reimage it as a painting. That is, instead of a photograph, the 
result looks as if it had been painted with watercolors or oils 
(your choice). You can also control the pressure of the brush 
strokes, the extent of coverage, even the texture of the virtual 
canvas on which the painting is made. Combining this with technology 
that will print a digital image on large-scale canvas or art paper, 
raises several points. One being: Why? Another being: Is it 
cheating?</p>

<p>This particularly matters to me, as I love doing this, and have 
been given an opportunity to present some of my work to a gallery 
owner, with the possible result of being given a <i>show</i> in the 
spring.</p>

<p>First of all, let's look at an example. Here's an original 
photograph.</p>

<img src="IMG_0704m.jpg" alt="HDR Photograph">

<p>And here's a &quot;painting&quot; generated by computer from that same 
photograph.</p>

<img src="Fossil%20Creek%20at%20Sally%20May.jpg" alt="Digital Painting">

<p>Now, this particular photo is, itself, manipulated. It's what's 
called an <a href="../HDR/Default.aspx">HDR photo</a>, with a 
wider range of light and dark than a photo can normally capture, 
compressed so that it can. This is the kind of thing a painter would 
do without thinking about it, because the human eye can capture a 
wider range than film or digital cameras can.</p>

<p>And of course, the main reason to create a painting rather than 
simply take a picture, is that, in theory, a painter can &quot;see&quot; more 
than the camera can. A painter can imbue emotional overtones, 
emphasizing some elements and not others, for example. A painting 
can possess &quot;<a href="http://en.wikipedia.org/wiki/Truthiness">truthiness</a>&quot; 
that exceeds the mere truth a camera can capture.</p>

<p>A computer cannot apply any of these enhancements to a photo, 
however, unless there's some way for the 
photographer/painter/programmer to indicate to the conversion 
program where and how this should happen. No programs I know of 
provide any such control.</p>

<p>Nevertheless. the use of photographic techniques to create 
paintings has a long history that far predates photography itself.</p>

<img class="Left Icon" src="400px-Pinhole-camera.svg.gif" alt="How a pinhole camera works.">

<p>The pinhole camera was first described by the 5th century BCE Mohist 
philosopher Mo Jing, who in ancient China mentioned the effect of an 
inverted image forming through a pinhole. Pinhole cameras were also 
described in the West around 1000 CE, where they were used to 
project an image onto tracing paper, which was then traced, 
providing an easy method of assisted drawing.</p>

<p>A larger version of a pinhole camera is the 
<i><a href="http://en.wikipedia.org/wiki/Camera_obscura">camera obscura</a></i>, 
which is Latin for &quot;dark chamber&quot;. This is very likely a technique 
used by Dutch painter Jan Vermeer for his series of perfectly 
composed paintings of interiors. Although he never described using 
the image from a <i>camera obscura</i>, his paintings have been 
digitally analyzed and there's really no other explanation for the 
flawless perspective or the perfect reflections in mirrors that 
appear in the painting (for example, above the virginal (a type of 
harpsichord) in the below reproduction of <i>The Music Lesson</i>.</p>

<img src="Vermeer.jpg" 

alt="The Music Lesson by Jan Vermeer suggests the use of the camera obscura as a painting tool."><p>
In more recent times, many painters have taken a color slide of a 
scene or subject they wished to paint, then projected the slide onto 
a canvas onto which they then applied paint. The technique allows 
for both the capturing of an ephemeral moment, photography's 
specialty, as well as the painter's emotional veneer to be applied, 
making the result a work of art.</p>

<p>But the coming of digital photography allows for photographs to 
be manipulated just as reality can be manipulated by a painter. 
Elements can be added or subtracted; colors shifted, blemishes 
removed. So why bother with paint, at all? Especially when photos 
can now be &quot;printed&quot; with paints directly on canvas, for archival 
and display purposes?</p>

<p>If I had to guess at the answer, I would say that it's because 
people <i>respond</i> differently to paintings than to photographs. 
I'm not saying the response to a photograph is <i>less than</i>, 
just that it's different, just as the response to a black-and-white 
photograph is different than the response to a full-color one is.</p>

<p>For example, take the following set of pictures, all from the 
same shot of Death Valley. First, allow me to present the original 
color photograph, taken on Kodacolor film in 1995.</p>

<img src="IMG0034.jpg" alt="Death Valley: color"><p>
It's a beautiful picture of a beautiful place. In terms of 
composition, it is balanced and intriguing. (I'm not bragging; those 
are terms a junior college art appreciation course would use to describe the 
shapes of light and dark and their relation to each other.)</p>

<p>Now, take a moment to appreciate the sere beauty of a monochrome 
rendition.</p>

<img src="IMG0034_mono.jpg" alt="Death Valley: monochrome">

<p>Essentially, this is the same photograph, with the only difference 
being the subtraction of color. Yet your response is likely to be 
quite different. In this case, the &quot;truthiness&quot; of Death Valley's 
heat and aridity and loneliness is emphasized. Even the vastness of 
the valley itself, beyond the foreground ridge, seems bigger (at 
least, to me).</p>

<p>Now, here's the same photo, rendered as a watercolor.</p>

<img src="FotoSketcher_IMG0034.jpg" alt="Death Valley: watercolor">

<p>To me, I immediately perceive this as more fanciful than the photo. 
These days, any photo can be faked, so we have grown to be a little 
suspicious of photography. Paintings, on the other hand, don't <i>
pretend</i> to represent actual reality; so we aren't on our guard 
when viewing them.</p>

<p>Because paintings provide less definition than photographs, many 
details are lost. For example, the delicate veins of the slopes at 
the far side of the valley, clearly visible in the photographic 
versions, are lost in the painting. This throws emphasis to the 
rocky foreground ridge. While the vastness of the valley is no 
longer so clear, the barrenness is emphasized. The plant life seems 
more desperate, more precarious. The rocks seem less &quot;just there&quot; 
and more like they've been carefully placed.</p>

<p>Not all photos lend themselves to being manipulated in this way. 
For example, I took a series of sunset pictures on the Apache Trail 
about 20 miles from my house. These are digital photos, which means 
there's no film &quot;grain&quot; (the bits of tiny blemishes visible in a 
photographic enlargement or through a magnifying glass). Converting 
the photo into an oil painting has the result of <i>introducing</i> 
something analogous to grain, imperfections in an otherwise 
breathtakingly smooth sea of color.</p>

<p>See if you don't agree. First, the photograph:</p>

<img src="Apache%20Trail%20Sunset%204.jpg" alt="Apache Trail Sunset: photograph">

<p>Then, the &quot;oil painting&quot; (oil makes a smoother image than 
watercolor):</p>

<img src="FotoSketcher_pache%20Trail%20Sunset%204.jpg" alt="Apache Trail Sunset: oil">

<p>While the oil version isn't objectionable, to my mind a large canvas
<a href="http://en.wikipedia.org/wiki/Gicl&eacute;e">Gicl&eacute;e</a> print, with 
no artifacts other than the weave of the canvas itself, would be the 
way to go with this picture.</p>

<p id=Extract>There are those who pick a medium&mdash;oils, acrylic, 
photography&mdash;and stick to it. There are others who pull in pieces, 
willy-nilly, using any tool they can find to produce the effect they 
want.</p>

<p>I'd be one of those.</p>

</asp:Content>
