<%@ Page 
    Language="vb" 
    AutoEventWireup="false" 
    MasterPageFile="~/Design/Site.Master" 
    CodeBehind="~/Design/Site.Master.vb" 
    %>
<%@ MasterType VirtualPath="~/Design/Site.Master" %>

<script runat="server">
	Public ThisPage As MillionLittlePieces.SiteMaster
	Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
		ThisPage = CType(Me.Master, MillionLittlePieces.SiteMaster)
		With ThisPage
			.Properties.Title = "Why Organica Web?"
			.Properties.Description = "Why a website's framework matters, and why OrganicaWeb is a good one."
			.Properties.Author = "Paul S Cilwa"
			.Properties.ThumbnailPath = "Badge.jpg"
			.Properties.Posted = "11/30/2024"
			.Properties.Keywords = "CilwaWeb, Website Design, OrganicaWeb"
		End With
	End Sub
</script>

<asp:Content ContentPlaceHolderID="CustomPageHead" runat="server" />

<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<img src="Badge.jpg">

<p id="Extract">I started OrganicaWeb because I needed a framework that could handle my personal website with over 
	2,000 pages without becoming unwieldy. Most other frameworks require you to use online editing tools, 
	which might work for sites with a dozen pages but falter beyond that scale. They often neglect crucial 
	features like automatic site navigation and force designers to manage mechanics over content. Tools like 
	the extensive CSS framework from W3Schools are powerful but overly complex and don't address navigation. 
	OrganicaWeb natively supports page banners, global navigation, and content panels, combining ASP, HTML, CSS, 
	VB.NET, and JavaScript to let designers focus on what matters most: the content.</p>

<p>OrganicaWeb is not intended for huge commericial sites like Amazon's or Walmart's, where the pages are
	actually generated by the server rather than actually written for each product. However, because it's
	a basic framework, it can definitely be extended to do whatever you want it to do.</p>

<p>The original site made use of what's called ASP Classic. When I began working with web technologies beyond
	Microsoft's FrontPage, ASP Classic was the standard for creating dynamic web pages. It allowed me to mix 
	server-side VBScript with HTML, but it had significant drawbacks. The code was interpreted rather than compiled, 
	leading to slower performance and scalability issues as projects grew. Its successor, ASP.NET, improved on 
	this by introducing a compiled, event-driven programming model using languages like VB.NET. It offered better 
	performance, a rich set of controls, and a more structured framework that integrated seamlessly with the 
	.NET ecosystem. This shift made developing complex, large-scale web applications more manageable and efficient.</p>

<p>Constructing an ASP.NET web page is fundamentally different from building a simple HTML page. With plain HTML, 
	each page is an isolated file, and shared elements like headers or navigation bars must be duplicated manually 
	across all pages&mdash;a tedious and error-prone process, especially for large websites. ASP.NET introduces 
	master pages, such as Site.Master, which act as templates to provide a consistent layout and design across 
	multiple pages. This concept is similar to how FrontPage used templates to standardize page elements, but 
	ASP.NET's master pages are more integrated and powerful within the .NET framework. By separating the content 
	from the design, ASP.NET makes it easier to maintain and update websites, allowing changes to the master page 
	to automatically reflect across all associated content pages.</p>

<p>This means, for example, that what should be a simple change&mdash;a different font for the page title,
	for example, or even a site-wide name change&mdash;in ASP does <i>not</i> require re-publishing the entire
	site, whereas in FrontPage a template change required every affected page to be re-published.</p>

<p>OrganicaWeb sites are inherently responsive, automatically adjusting to fit the size and proportions of any 
	device. By utilizing fluid grids and flexible images in combination with CSS media queries, the framework 
	ensures that pages render properly on desktops, tablets, and smartphones. This approach eliminates the need 
	for separate mobile versions of the site. Instead, the same codebase adapts to different screen sizes, allowing 
	the designer (me) to focus on creating content without worrying about device-specific layouts.</p>

<p>In developing OrganicaWeb, my goal was to create a framework that streamlines the process of building and managing 
	large-scale content-driven websites. By addressing the limitations of existing tools and focusing on seamless 
	navigation, responsive design, and content-centric development, OrganicaWeb empowers designers to work more 
	efficiently. In the upcoming pages, I'll dive deeper into each component of the framework, providing detailed 
	insights and guidance. Whether you're looking to enhance your current site or embark on a new project, I hope 
	you'll find OrganicaWeb to be a valuable resource for your web development needs.</p>

</asp:Content>
