<%@ Page 
    Language="vb" 
    AutoEventWireup="false" 
    MasterPageFile="~/Design/Site.Master" 
    CodeBehind="~/Design/Site.Master.vb" 
    %>
<%@ MasterType VirtualPath="~/Design/Site.Master" %>

<script runat="server">
    Public ThisPage As MillionLittlePieces.SiteMaster
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        ThisPage = CType(Me.Master, MillionLittlePieces.SiteMaster)
        With ThisPage
            .Properties.Title = "Chris' and Paul's Trip to Vermont"
            .Properties.Description = "All about my very first multi-state trip -- without parents!"
            .Properties.Keywords = "Places,,Cross-Country,Travel"
            .Properties.ThumbnailPath = "001.Title.jpg"
            .Properties.Occurred = "09/20/1969"
            .Properties.Posted = "05/05/2024"
        End With
    End Sub
</script>

<asp:Content ContentPlaceHolderID="CustomPageHead" runat="server" />

<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<img src="001.Title.jpg" />
<img src="002.Credit.jpg" />
    
<p id=Extract>In mid-September, 1969, my friend Chris and I carefully saved our money until, in September, 
    1969, we were ready to make the journey of a lifetime (so far!): From Florida all the way 
    up to Vermont (where I had lived as a kid) and back again.</p>

<p>When Chris first came to St. Joseph Academy, he had called himself by his first 
    name, John; so that's what I called him, too. However, his full name was 
    John Christopher Palmes, and for some reason at home he was called <q>Chris</q>. 
    As so many kids do, he had decided to experiment 
    with using his <q>other</q> name when he transferred to a new school. But as I spent 
    more time with him in the context of his family, I found myself calling him 
    <q>Chris</q> as well. And so, that is how I will refer to him for the remainder of 
    this memoir.</p>

<p>The reason we had mid-September available to us for a trip, is that a) Chris 
    wasn't going to school in the fall; and b) I was to attend an electronics school 
    that didn't start until mid-October. The reason we had to wait 
    <i>until</i> mid-September is that I was working as a lifeguard at the Ponce de Leon 
    Motor Lodge and that was when that seasonal job ended.</p>

<img src="003.My_New_Car.jpg" />

<p>Our means of transportation was to be <i>my new car!</i> I hadn't previously owned a 
    car, ever; but with $1200 from my school loan, I was able to buy one. It 
    turned out to be a white 1966 Plymouth Valiant with red interior. My monthly payments
    were $32.38. I was now ready to go.</p>

<h3>To Fort Lauderdale, Florida</h3>

<aside>
    <p>These are (virtually) all the original photos from 1969. They were taken
        mostly on Kodak Ektachrome film, which I preferred over Kodachrome
        for its brighter, more saturated colors. (These days, photos taken
        with an iPhone more resemble Kodachrome, while photos taken with a
        Samsung look more like Ektachrome.)</p>
    <p>Of course, old color photos, even slides (especially slides!) fade and
        discolor with time. But I've been able to digitize the original photos,
        and then used a suite of aritifical intelligence tools as well as conventional
        digital techniques to freshen them so they look like they were taken
        yesterday! (With a Samsung!)</p>
    <p>There are a very few images here either taken from the web, or
        generated by AI. But I think you'll be able to spot those if you care.</p>
</aside>


</asp:Content>
